AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Sample SAM Template
# More info https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification-template-anatomy.html
Globals:
  Function:
    Runtime: java8
    Timeout: 60
    MemorySize: 512
    Environment:
      Variables:
        REGION: ap-northeast-1


Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: modules/adapter/presentation/notifydaysshift/target/scala-2.13/notifyDaysShift.jar
      Handler: shiftdays.App::handleRequest
      FunctionName: notifyDaysShift
#      Events:
#        HelloWorld:
#          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
#          Properties:
#            Path: /hello
#            Method: get
#        HelloWorld2:
#          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
#          Properties:
#            Path: /hello/{proxy+}
#            Method: get
